<ul class="mono_list type_code_columns_4">
	<li><span>0</span><span>None</span></li>
	<li><span>1</span><span>TES4</span></li>
	<li><span>2</span><span>Group</span></li>
	<li><span>3</span><span>GMST</span></li>
	<li><span>4</span><span>TextureSet</span></li>
	<li><span>5</span><span>MenuIcon</span></li>
	<li><span>6</span><span>Global</span></li>
	<li><span>7</span><span>Class</span></li>
	<li><span>8</span><span>Faction</span></li>
	<li><span>9</span><span>HeadPart</span></li>
	<li><span>10</span><span>Hair</span></li>
	<li><span>11</span><span>Eyes</span></li>
	<li><span>12</span><span>Race</span></li>
	<li><span>13</span><span>Sound</span></li>
	<li><span>14</span><span>AcousticSpace</span></li>
	<li><span>15</span><span>Skill</span></li>
	<li><span>16</span><span>Effect</span></li>
	<li><span>17</span><span>Script</span></li>
	<li><span>18</span><span>LandTexture</span></li>
	<li><span>19</span><span>Enchantment</span></li>
	<li><span>20</span><span>Spell</span></li>
	<li><span>21</span><span>Activator</span></li>
	<li><span>22</span><span>TalkingActivator</span></li>
	<li><span>23</span><span>Terminal</span></li>
	<li><span>24</span><span>Armor</span></li>
	<li><span>25</span><span>Book</span></li>
	<li><span>26</span><span>Clothing</span></li>
	<li><span>27</span><span>Container</span></li>
	<li><span>28</span><span>Door</span></li>
	<li><span>29</span><span>Ingredient</span></li>
	<li><span>30</span><span>Light</span></li>
	<li><span>31</span><span>Misc</span></li>
	<li><span>32</span><span>Static</span></li>
	<li><span>33</span><span>StaticCollection</span></li>
	<li><span>34</span><span>MoveableStatic</span></li>
	<li><span>35</span><span>PlaceableWater</span></li>
	<li><span>36</span><span>Grass</span></li>
	<li><span>37</span><span>Tree</span></li>
	<li><span>38</span><span>Flora</span></li>
	<li><span>39</span><span>Furniture</span></li>
	<li><span>40</span><span>Weapon</span></li>
	<li><span>41</span><span>Ammo</span></li>
	<li><span>42</span><span>NPC</span></li>
	<li><span>43</span><span>Creature</span></li>
	<li><span>44</span><span>LeveledCreature</span></li>
	<li><span>45</span><span>LeveledCharacter</span></li>
	<li><span>46</span><span>Key</span></li>
	<li><span>47</span><span>AlchemyItem</span></li>
	<li><span>48</span><span>IdleMarker</span></li>
	<li><span>49</span><span>Note</span></li>
	<li><span>50</span><span>ConstructibleObject</span></li>
	<li><span>51</span><span>Projectile</span></li>
	<li><span>52</span><span>LeveledItem</span></li>
	<li><span>53</span><span>Weather</span></li>
	<li><span>54</span><span>Climate</span></li>
	<li><span>55</span><span>Region</span></li>
	<li><span>56</span><span>NAVI</span></li>
	<li><span>57</span><span>Cell</span></li>
	<li><span>58</span><span>Reference</span></li>
	<li><span>59</span><span>ACHR</span></li>
	<li><span>60</span><span>ACRE</span></li>
	<li><span>61</span><span>PMIS</span></li>
	<li><span>62</span><span>PGRE</span></li>
	<li><span>63</span><span>PBEA</span></li>
	<li><span>64</span><span>PFLA</span></li>
	<li><span>65</span><span>WorldSpace</span></li>
	<li><span>66</span><span>Land</span></li>
	<li><span>67</span><span>NavMesh</span></li>
	<li><span>68</span><span>TLOD</span></li>
	<li><span>69</span><span>DIAL</span></li>
	<li><span>70</span><span>INFO</span></li>
	<li><span>71</span><span>Quest</span></li>
	<li><span>72</span><span>Idle</span></li>
	<li><span>73</span><span>Package</span></li>
	<li><span>74</span><span>CombatStyle</span></li>
	<li><span>75</span><span>LoadScreen</span></li>
	<li><span>76</span><span>LeveledSpell</span></li>
	<li><span>77</span><span>ANIO</span></li>
	<li><span>78</span><span>WaterForm</span></li>
	<li><span>79</span><span>EffectShader</span></li>
	<li><span>80</span><span>TOFT</span></li>
	<li><span>81</span><span>Explosion</span></li>
	<li><span>82</span><span>Debris</span></li>
	<li><span>83</span><span>ImageSpace</span></li>
	<li><span>84</span><span>ImageSpaceModifier</span></li>
	<li><span>85</span><span>ListForm</span></li>
	<li><span>86</span><span>Perk</span></li>
	<li><span>87</span><span>BodyPartData</span></li>
	<li><span>88</span><span>AddonNode</span></li>
	<li><span>89</span><span>ActorValueInfo</span></li>
	<li><span>90</span><span>RadiationStage</span></li>
	<li><span>91</span><span>CameraShot</span></li>
	<li><span>92</span><span>CameraPath</span></li>
	<li><span>93</span><span>VoiceType</span></li>
	<li><span>94</span><span>ImpactData</span></li>
	<li><span>95</span><span>ImpactDataSet</span></li>
	<li><span>96</span><span>ARMA</span></li>
	<li><span>97</span><span>EncounterZone</span></li>
	<li><span>98</span><span>Message</span></li>
	<li><span>99</span><span>Ragdoll</span></li>
	<li><span>100</span><span>DOBJ</span></li>
	<li><span>103</span><span>Weapon Mods</span></li>
	<li><span>106</span><span>Recipe</span></li>
	<li><span>107</span><span>Recipe Category</span></li>
	<li><span>108</span><span>CasinoChip</span></li>
	<li><span>115</span><span>CaravanCard</span></li>
	<li><span>116</span><span>FactionCurrency</span></li>
	<li><span>101</span><span>LightingTemplate</span></li>
	<li><span>102</span><span>SoundFile</span></li>
	<li><span>200</span><span>Actor (for ref walking only)</span></li>
	<li><span>201</span><span>Inventory Object (for ref walking only)</span></li>
    <li><span>301</span><span>Map Marker Refs</span></li>
</ul>