<ul class="mono_list type_code_columns_4">
	<li><span>0</span><span>Aggression</span></li>
	<li><span>1</span><span>Confidence</span></li>
	<li><span>2</span><span>Energy</span></li>
	<li><span>3</span><span>Responsibility</span></li>
	<li><span>4</span><span>Mood</span></li>
	<li><span>5</span><span>Strength</span></li>
	<li><span>6</span><span>Perception</span></li>
	<li><span>7</span><span>Endurance</span></li>
	<li><span>8</span><span>Charisma</span></li>
	<li><span>9</span><span>Intelligence</span></li>
	<li><span>10</span><span>Agility</span></li>
	<li><span>11</span><span>Luck</span></li>
	<li><span>12</span><span>ActionPoints</span></li>
	<li><span>13</span><span>CarryWeight</span></li>
	<li><span>14</span><span>CritChance</span></li>
	<li><span>15</span><span>HealRate</span></li>
	<li><span>16</span><span>Health</span></li>
	<li><span>17</span><span>MeleeDamage</span></li>
	<li><span>18</span><span>DamageResistance</span></li>
	<li><span>19</span><span>PoisonResistance</span></li>
	<li><span>20</span><span>RadResistance</span></li>
	<li><span>21</span><span>SpeedMultiplier</span></li>
	<li><span>22</span><span>Fatigue</span></li>
	<li><span>23</span><span>Karma</span></li>
	<li><span>24</span><span>XP</span></li>
	<li><span>25</span><span>Head</span></li>
	<li><span>26</span><span>Torso</span></li>
	<li><span>27</span><span>LeftArm</span></li>
	<li><span>28</span><span>RightArm</span></li>
	<li><span>29</span><span>LeftLeg</span></li>
	<li><span>30</span><span>RightLeg</span></li>
	<li><span>31</span><span>Brain</span></li>
	<li><span>32</span><span>Barter</span></li>
	<li><span>33</span><span>BigGuns</span></li>
	<li><span>34</span><span>EnergyWeapons</span></li>
	<li><span>35</span><span>Explosives</span></li>
	<li><span>36</span><span>Lockpick</span></li>
	<li><span>37</span><span>Medicine</span></li>
	<li><span>38</span><span>MeleeWeapons</span></li>
	<li><span>39</span><span>Repair</span></li>
	<li><span>40</span><span>Science</span></li>
	<li><span>41</span><span>SmallGuns</span></li>
	<li><span>42</span><span>Sneak</span></li>
	<li><span>43</span><span>Speech</span></li>
	<li><span>44</span><span>Throwing</span></li>
	<li><span>45</span><span>Unarmed</span></li>
	<li><span>46</span><span>InventoryWeight</span></li>
	<li><span>47</span><span>Paralysis</span></li>
	<li><span>48</span><span>Invisibility</span></li>
	<li><span>49</span><span>Chameleon</span></li>
	<li><span>50</span><span>NightEye</span></li>
	<li><span>51</span><span>DetectLifeRange</span></li>
	<li><span>52</span><span>FireResistance</span></li>
	<li><span>53</span><span>WaterBreathing</span></li>
	<li><span>54</span><span>RadLevel</span></li>
	<li><span>55</span><span>BloodyMess</span></li>
	<li><span>56</span><span>UnarmedDamage</span></li>
	<li><span>57</span><span>Assistance</span></li>
	<li><span>58</span><span>ElectricResist</span></li>
	<li><span>59</span><span>FrostResist</span></li>
	<li><span>60</span><span>EnergyResist</span></li>
	<li><span>61</span><span>EmpResist</span></li>
	<li><span>62</span><span>Variable01</span></li>
	<li><span>63</span><span>Variable02</span></li>
	<li><span>64</span><span>Variable03</span></li>
	<li><span>65</span><span>Variable04</span></li>
	<li><span>66</span><span>Variable05</span></li>
	<li><span>67</span><span>Variable06</span></li>
	<li><span>68</span><span>Variable07</span></li>
	<li><span>69</span><span>Variable08</span></li>
	<li><span>70</span><span>Variable09</span></li>
	<li><span>71</span><span>Variable10</span></li>
	<li><span>72</span><span>IgnoreCrippledLimbs</span></li>
	<li><span>73</span><span>Dehydration</span></li>
	<li><span>74</span><span>Hunger</span></li>
	<li><span>75</span><span>SleepDeprevation</span></li>
	<li><span>76</span><span>DamageThreshold</span></li>
</ul>