//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVSE_Docs_Manager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string />
  <string>Actor_Flags</string>
  <string>Actor_Value_Codes</string>
  <string>Ammo_Trait_ID</string>
  <string>Attack_Animations</string>
  <string>Biped_Masks</string>
  <string>Biped_Path_Codes</string>
  <string>Control_Codes </string>
  <string>Creature_Type_Codes</string>
  <string>Default_Forms</string>
  <string>DirectX_Scancodes </string>
  <string>Equip_Slots</string>
  <string>Equip_Type</string>
  <string>Form_Type_IDs </string>
  <string>Format_Specifiers </string>
  <string>Map_Marker_Type </string>
  <string>Perk_Entry_Point</string>
  <string>Radio_Broadcast_Type </string>
  <string>Reload_Animations </string>
  <string>Weapon_Flags </string>
  <string>Weapon_Hand_Grips </string>
  <string>Weapon_Mod </string>
  <string>Weapon_Type</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TypeCodes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TypeCodes"]));
            }
            set {
                this["TypeCodes"] = value;
            }
        }
    }
}
